### PR TITLE
Some misc changes to the website

### PR DESCRIPTION
**Pull request by grctest**
Removed the underline from header/footer links
Removed the fontawesome icons
Made the header dropdown titles black instead of grey
Made the footer hyperlinks not bold
Changed contact details
Heavily cut back the security guide
Merged the trade & spend dropdown menus

### CODE REVIEW

**Comment by barton2526** [comment]
Bitker logo is very small (128x26 pixels).  Can we find a larger one so it doesn't look so grainy when upscaled?

**Comment by grctest** [comment]
RE: robots.txt it would appear to have been edited outwith the github settings, see the [live contents](https://gridcoin.us/robots.txt): 

```
User-agent: SemrushBot
Disallow: *

User-agent: *
Disallow: /index.php
Disallow: /download
```

Compared to the github version:
```
# robotstxt.org/

User-agent: *
```

At the moment, some bot appears to have been banned from indexing gridcoin and all user-agents are prevented from indexing downloads which is fair but then also a non existent index php file? 

What should be an appropriate robots indexing text file?

**Comment by barton2526** [comment]
That's extremely strange that the live robots.txt file does not match what is being pushed from Github.  😕

**Comment by grctest** [comment]
I've updated the bitker logo, I had to make the text white because it was almost invisible otherwise.

**Comment by barton2526** [comment]
We'll need to look into the robots.txt thing further, but otherwise approved 👍

**Pull request merged**
