### PR TITLE
Home Page: Explain What "Secures Network" Means

### LINKED ISSUE #34: Explain why staking helps secure the network
In [@lennstar's post](https://steemit.com/gridcoin/@lennstar/why-people-do-not-keep-their-wallets-open-all-the-time) why people do not keep their wallets online, one of the points (#7) is that people might not know that it's needed. Gridcoin.us only mentions "Secure the network" but does not explain anywhere how you can secure the network or why it should be done.

### PR DESCRIPTION
**Pull request by RoboticMind**
Adds a tooltip that says "Whether running a wallet in these modes helps increase decentralization", This probably can be made better, but it was difficulty to think of anything concise that clarified a bit more than this. Open to any other suggestions

Closes #34

### CODE REVIEW

**Comment by barton2526** [comment]
I'm not a huge fan of the wording.  I'll try to brainstorm a better one today

**Comment by barton2526** [comment]
how about "contributes to network decentralization"?

**Comment by RoboticMind** [comment]
Changed it to that now

**Comment by RoboticMind** [comment]
@barton2526 do you think this is good to merge now?

**Pull request merged**
