### PR TITLE
Update _solo_boinc_intro.htm

### PR DESCRIPTION
**Pull request by makeasnek**
Add sciencestats faucet to make new user onboarding easier

### CODE REVIEW

**Comment by nathanielcwm** [comment]
You should add your faucet to exchange.htm too. I think putting your faucet directly in the guide, with the implications that it's the only faucet - due to the wording, is a definite issue.

**Comment by makeasnek** [comment]
I don't think it implies this is the _only_ faucet, but I agree there is a potential conflict of interest here with me adding my own faucet to the guides. That's why it's good that y'all review these PRs. The faucet was built specifically to solve the problem of solo crunchers needing GRC to start, it's the fastest way for people to get the free GRC required outside of begging in discord. Other faucets require days and multiple visits to build up enough GRC, even if you are being strategic with which ones you hit when.

We could, of course, list multiple faucets, but I worry we will confuse users who will try to use all of them or not know which ones to use. Ideally we would just have every new user press a button for 2 free GRC to make a beacon, this is about as close as we can get to that. There should be one default path for users and we should eliminate confusing choices whenever possible. Though we could say "faucet x is suggested, but you can see a list of more faucets at page y".

Somewhat related, there will be some usability improvements to the faucet this week to make it a little simpler to use.

**Comment by nathanielcwm** [comment]
TBH I'm personally of the opinion that the notice is unnecessary now with MRC and that it duplicates the information on acquire-grc.htm - which does list multiple faucets (including yours after #383)

**Comment by makeasnek** [comment]
The notice in its entirety or just that it's linking to the sciencestats faucet? I think the notice needs to be there. And if we are saying users are going to need GRC to start earning rewards, we should be telling them at the same time that they'll be easily able to acquire that starter GRC for free. Otherwise, they'll either not start the process (and therefore not get to the other faucets page), or start the pool guide.

The acquire GRC page is... a mess. As a new user it presents a massive supermarket effect where it's not clear what the best/easiest/fastest way to acquire GRC is and the choices are a little overwhelming. I think that's a good generic acquire GRC page, but not a good "acquire the 2 GRC you need to start" page. This guide should say "here is the the easiest, most obvious route to get the 2 grc you need to start. For more options, or if you want to buy GRC, see this other page". Maybe sciencetats is that route, maybe it's begging on discord, maybe it's something else, but I would like to see it simplified in such a way.

**Comment by nathanielcwm** [comment]
> The notice in its entirety or just that it's linking to the sciencestats faucet?

In general but you do put up a good point that I didn't think about.

**Comment by RoboticMind** [comment]
Not sure I am a fan of putting a link to a specific faucet here due to the implication that it is the only faucet. Maybe if the wording was "a faucet such as \<link1\> or \<link2\>"

**Comment by makeasnek** [comment]
> Not sure I am a fan of putting a link to a specific faucet here due to the implication that it is the only faucet. Maybe if the wording was "a faucet such as <link1> or <link2>"

I have updated the patch to include a link to some other faucet.

The point of the sciencestats faucet being a one-stop-shop for new crunchers is to avoid the confusing step of having to figure out _which_ is the best faucet to use for this circumstance. If the objection is based out of me having a potential conflict of interest, I would gladly transfer the faucet to a community-run server (and have y'all pay the hosting). Which is currently about $20 USD/month. This faucet is a money sink for me and probably always will be. It was created specifically to solve the "new user doesn't have 2 GRC to get a beacon" problem, which I think it a significant hurdle for new users who are not already familiar with crypto (don't have exchange accounts or other crypto to trade for GRC & have no fiat on-ramp).

I think it is wise to suggest a specific faucet, while saying others also exist. If we say you can use faucet A, B, or C then users will think they need to decide which one to use and have to read up on them. They may think each faucet is equally good at getting them their starter GRC which just isn't the case. And so, they may choose B or C which take a week to get enough coins to get started, get frustrated, and leave. None of that is is UX.

**Comment by makeasnek** [comment]
Can we get this merged? Are there any outstanding objections w/ the recent changes?

**Comment by barton2526** [comment]
So I still have two issues here. First, the title of the PR isn't descriptive at all. Just put something like "Add sciencestats faucet to make new user onboarding easier".

Second, and more fundamentally, I agree with what RoboticMind said. We shouldn't be listing just one faucet. There is a real conflict of interest here being that you operate it and are putting this PR up. Frankly, sciencestats hasn't existed long enough to warrant being the only listed faucet on this page.

If you want to put sciencestats on the faucet page, that's fine and I would merge 100%. Listing sciencestats _only_ and then listing the other faucets almost makes them seem like second class.

**Comment by makeasnek** [comment]
Alright closing this PR. This really seems like a no-brainer to me, the faucet is a net loss financially for me and always will be. It's a win for users but if you don't want it listed then I'm not going to fight you on it. I believe it is pointless to put it as "one of x faucets" in a list, it just complicates an onboarding experience that is already too complicated. Here's yet another person from twelve days ago who gave up on crunching because the onboaring experience was too complicated. This happens all the time and most people don't seek support or complain about it online, they just move on to other coins.

image

The other faucets _are_ second class for this purpose, they take days and dozens of captchas to dispense enough coins, and because of faucet abuse they end up being a drain on the Gridcoin community's limited resources, that GRC could be much better spent on other things. This faucet is designed to solve a very specific problem with onboarding and does it well. For existing BOINC users, they fill out one captcha, change their username, click a button and they get all the coins the need for a beacon in < 60 seconds. It isn't aesthetically pleasing, but it gets the job done.

But instead we will give the user a list of faucets and pray that they can understand how they all work, what their timeouts and minimums are, and pick which one is best for them. From a UX perspective it is frankly a nightmare.

**Pull request closed without merging**
