### PR TITLE
Update whitelist

### PR DESCRIPTION
**Pull request by ShmoogleOsukami**
Added DHEP
Updated Stats link for amicable numbers
Removed CSG
Removed VTGU - Graylisted.

When merging we should probably do a squash merge to clean up these damn commits that run rampant in my repos :/

### CODE REVIEW

**Comment by barton2526** [comment]
Please clean up the commits...

**Comment by ShmoogleOsukami** [comment]
fml that didnt work. I feel like I should just close this and fix my branches and github fork

**Comment by barton2526** [comment]
>Updated Stats link for amicable numbers

I'm noticing a lot of other broken links to gridcoinstats as well.... LHC for one.  Seems any project with a space (underscore?) is impacted.

**Comment by barton2526** [comment]
Addresses 2/3 of #187

**Comment by barton2526** [comment]
> The page build failed for the `master` branch with the following error:
> 
> There was a YAML syntax error on line 154 column 3 in `_data/whitelist.yml`: `did not find expected key while parsing a block mapping`. For more information, see https://help.github.com/en/articles/page-build-failed-invalid-yaml-in-data-file.

**Pull request merged**
