### PR TITLE
Update addnodes.md

### PR DESCRIPTION
**Pull request by throny**
added 1 more node

### CODE REVIEW

**Comment by RoboticMind** [comment]
One of the other web developers/maintainers was saying that it may be better to wait until cycy adds it to there script before merging. 

Know you were saying that you were going to PM cycy. Any luck with that?

**Comment by throny** [comment]
@RoboticMind Yup, messaged him but no reply yet. Since it is not urgent, that can also wait :)

**Comment by barton2526** [comment]
@cyrossignol

**Comment by throny** [comment]
Addnode was added to the cycy script :)

**Comment by RoboticMind** [comment]
Hmm @throny it shows up as unreachable in cycy's script

**Comment by throny** [comment]
Hey @RoboticMind - thats right, because I was too tired and made a mistake while updating the wallet. Will bring back up in the next hours.

**Comment by RoboticMind** [comment]
Looks like it's online now

**Comment by RoboticMind** [comment]
@barton2526 do you think this is good to merge?

**Comment by barton2526** [comment]
Fine with me.

**Pull request merged**
