### PR TITLE
Slight wording change, Changes link colour for easier readability.

### PR DESCRIPTION
**Pull request by ShmoogleOsukami**
First pull request ever done soo. yeah.

I've changed the wording ever so slightly and added a missing word, Still conveys the same message but reads better in my opinion, 
I've also changed the link colour to be easier to read against the gray background. 

Tell me what you think.
Edit: we might need a wider discussion on weather we should brighten the purple across the whole site for consistency or something.

### CODE REVIEW

**Comment by ShmoogleOsukami** [comment]
[Imgur link demonstrating colour change.](https://i.imgur.com/EyYp8ye.png)

**Comment by grctest** [comment]
Could make it site wide but would have to avoid affecting the header/footer links

**Comment by ShmoogleOsukami** [comment]
> Could make it site wide but would have to avoid affecting the header/footer links

It'll be a matter of going through all the pages where needed, Once I get everything working on WSL I'll have a look and test on a local setup

**Comment by ShmoogleOsukami** [comment]
ooooh Errm I broke this pull request. Note to self use branches.

**Comment by ShmoogleOsukami** [comment]
I'll sort out branches and start with the CSS inline removal first.

**Pull request closed without merging**
