### PR TITLE
Whitelist improvements + Fix for Linux BOINC installers

### PR DESCRIPTION
**Pull request by makeasnek**
- Adds AMD and NVIDIA badges to whitelist so users can easily determine if project supports their hardware. Update YAML file to support noting whether or not projects support AMD or NVIDIA.
- Add note about Linux installers for BOINC being broken right now, with link to workaround
- Reduce amount of bolding in top section of solo crunching guide, it was a little much.

### CODE REVIEW

**Comment by makeasnek** [comment]
I will get this updated tonight

**Comment by makeasnek** [comment]
> My only issue here is the NVIDIA logo looks weird with the transparency on the green background. Can we try to find the logo with background? image

Yes I can get this added tonight

**Comment by makeasnek** [comment]
Fixed

**Comment by barton2526** [comment]
the width of the icons being different is a little weird, but that's nitpicky. If you don't care, I don't care

**Comment by RoboticMind** [comment]
Does make the other image a bit larger to download (12kb vs 100kb), not too bad for an image though. Can save a tiny bit without any lossy compression by using a png optimizer (~2kb here - usually it's more than that). Here's that version:

nvidia_badge_old


`optipng -o7 -zm1-9 nvidia_badge.png`

**Review by RoboticMind — APPROVED** [review]
uACK

**Pull request merged**
