### PR TITLE
General: Site Cleanup | Part 2

### PR DESCRIPTION
**Pull request by RoboticMind**
* Better accessibility for users that use screen readers
  * Add role="main" to the divs with the main content
  * Adds a jump to content button  
  * Give the downloads button a label (also helps non-screen reader users too)
* Rename "Investor" to "Non-Cruncher" to better reflect what it is supposed to mean
* Add rel=canonical SEO tag and remove unneeded author tag
* Cleans up some links across the site
* Mention 5.1.0 release in the blog
* Remove an a never used image
* Update the 404 Page
* Update Copyright year

### CODE REVIEW

**Review by ShmoogleOsukami — APPROVED** [review]
Looks good to me.

**Comment by barton2526** [comment]
If these changes for the investor/non-cruncher name go live on the website, the wallet and the site will be in conflict.  I don't think it's a good idea to update documentation on one resource without the wallet's naming updated as well.  Is there a tracking issue on the main repo to follow the status of these name changes in the wallet itself?

**Comment by RoboticMind** [comment]
I was asking Jim about this, but he was saying how it takes a fair amount of work to update in the client. He agreed it needed to be changed. I haven't opened an issue yet

I can also potentially add a mention that it is currently called "investor" in the wallet on the guides pages where I think the terminology in the wallet vs site matters the most

**Comment by RoboticMind** [comment]
@barton2526 added a mention in the guide that the wallet calls it "investor". If that looks good with that change, can you merge it?

**Pull request merged**
