### PR TITLE
Remove Flyp.me

### PR DESCRIPTION
**Pull request by barton2526**

### CODE REVIEW

**Comment by wilkart** [comment]
Have we contacted Flyp.Me team to ask what is their plan? Maybe their are working to bring it back exchangable and removing it from our website is "not a good look …"?

**Comment by barton2526** [comment]
This is not the place for these kinds of discussions. Jim Owens has contact information for Flyp.me. Talk with him about it.

**Comment by wilkart** [comment]
Here is an action of removal, here is the 1st place to ask why.

**Comment by barton2526** [comment]
Flyp.me was removed from the list of active exchanges because it hasn't supported Gridcoin for several months. This was done in response to a request on reddit: https://www.reddit.com/r/gridcoin/comments/1dm9d0m/no_flypme/

If you have further questions take them up with Flyp.me

**Pull request merged**
