### PR TITLE
Implement A Basic Wiki System

### PR DESCRIPTION
**Pull request by RoboticMind**
Creates a groundwork for a system to replace the current wiki. Uses .md files located in the /Wiki folder. Right now just two pages are there. I want to get a basic system working then do another PR for updating the wiki pages.

Also it does gets rid of the /Dev/RPC reference page and link and replaces with a new RPC Wiki page. The main Gridcoin Wiki link is left as is for now, but will be updated in the future 

In the _layout folders there's now a new entry for wiki pages, and there's some css styling for wiki pages

### CODE REVIEW

**Comment by jamescowens** [comment]
I really wanted this to use the /doc/wiki from the main repo. This ensures the content of the wiki on the main website is synchronized with that on the actual codebase, and allows the updating to occur automatically when the master branch is updated.

**Comment by RoboticMind** [comment]
So looking into how to do that, it looks like that would likely require using git submodules which don't automatically update. I suppose we could setup a bot to check every so often and update it using something like GitHub actions

Also, I didn't see a /doc/wiki folder in the Gridcoin-Research. I also didn't see it on your fork on the branch new_wiki_in_docs. Is it somewhere else or is it not in any repo yet?

**Comment by jamescowens** [comment]
It would help if I pushed the commit! :) Done.

**Comment by jamescowens** [comment]
I think the github actions would work, right? We can trigger that on commit to master.

**Comment by jamescowens** [comment]
The reason I want it this way is that the behavior of the wallet changes when a new release is published. This method ensures the published documentation is synchronized with the release.

**Comment by RoboticMind** [comment]
Hmm, it looks like git submodules can't clone just one folder, but they clone the entire repository. That might be an issue. Maybe we just have a wiki repo separate (not in the wiki tab, but the actual repo) and have it as a submodule in both the Gridcoin-Research and Gridcoin-Site. Although cloning it on some git clients won't download submodules, so we could make a note on how to manually do that if it didn't download for you

**Pull request merged**
