### PR TITLE
Minimize & Optimize Downloads

### PR DESCRIPTION
**Pull request by RoboticMind**
* Minimize Open Iconic CSS
* Minimize the Details Element Polyfill
* Make the fetch-release.js only run if on the index page where its needed

### CODE REVIEW

**Comment by barton2526** [comment]
What are the actual size savings on the minifications?  Most of the time CSS minification is more trouble than it's worth frankly.

Additionally, is there any cost incurred on the if statement to check whether we are looking at the index page for the fetch-release.js run?

**Comment by barton2526** [comment]
Further on this, is there an actual difference in page load time with the minified files?  How much of a performance gain are we talking about here for this PR?  If it's just a millisecond I would question whether it's worth the bother.

**Comment by RoboticMind** [comment]
It saves around a tenth of a second from my testing (both from looking at chrome's lighthouse report and from testing with Firefox network tools). 

I was not able to notice any significant build time change from the if statement. It looked like it was still in margin of error from testing the differences (seems to vary about 20 millisecond even on the same build with zero changes)

**Comment by barton2526** [comment]
And the file size savings?

**Comment by RoboticMind** [comment]
Smaller than the time savings at ~5.5kb between the two files. I suspect the time savings is not from download speeds themselves as I saw the same speedup testing in localhost with no throttling

**Comment by barton2526** [comment]
I'm confused.  If the time savings isn't from the smaller files being downloaded, where is the tenth of a second coming from?  Minification of CSS should just be removed whitespace and simplifying variable names.

**Comment by RoboticMind** [comment]
Looking at Firefox's performance tab thing, it looks like it ends up spending less time on the DOM for some reason. I think it might parsing related and or just able to be able to queue things more effectively to spend less time on the DOM somehow.

**Pull request closed without merging**
